### ISSUE TITLE
Reopening / switching to app doesn't work if mock service is running

### ISSUE THREAD

**Issue by ghost** [warren-bank/Android-Mock-Location#15]
Unfortunately I'm not able to switch back to Android-Mock-Location while the mock service is running. The app doesn't really crash, although it looks like it does. I have to force close the app to get to the UI again. Any clue what's going on?
I'm on Android 13 / LineageOS 20.

<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://s11.gifyu.com/images/ezgif-3-a101231def.gif">
  <source media="(prefers-color-scheme: light)" srcset="https://s11.gifyu.com/images/ezgif-3-a101231def.gif">
  <img alt="Screen recording" src="https://s11.gifyu.com/images/ezgif-3-a101231def.gif">
</picture>

**Comment by warren-bank** [comment]
I've been unable to reproduce using LineageOS 20.
Would it be possible for you to summarize the error being reported by logcat?
Also, when you start the service in your video.. is a foreground service notification added? (I didn't see one.)
Here is a summary of what I tried..

- - - -

#### successfully tested:

* [release: v2.3.1](https://github.com/warren-bank/Android-Mock-Location/releases/tag/service%2Fv02.03.01)
  - [apk for app](https://github.com/warren-bank/Android-Mock-Location/releases/download/service%2Fv02.03.01/Mock-my-GPS-002.03.01-03API-withAllLanguageTranslations-withAospLocationProviders-release.apk)
  - [apk for UnifiedNlp backend plugin](https://github.com/warren-bank/Android-Mock-Location/releases/download/service%2Fv02.03.01/Mock-my-GPS-UnifiedNlp-Backend-002.03.01-09API-withAllLanguageTranslations-release.apk)
* results:
  - OK: app only
  - OK: app w/ UnifiedNlp backend plugin

- - - -

#### intentionally tested with apks having mismatched signatures:

* v2.3.1
  - release build of app from github
  - debug build of UnifiedNlp backend plugin
* results (logcat summary):
  ```text
    java.lang.RuntimeException
      unable to start service:
        com.github.warren_bank.mock_location.service.LocationService
      caused by:

    java.lang.SecurityException
      not allowed to bind to service Intent:
        com.github.warren_bank.mock_location.service.microg_nlp_backend.LocationService
      at
        com.github.warren_bank.mock_location.service.microg_nlp_backend.UnifiedNlpManager.init()
      at
        com.github.warren_bank.mock_location.service.looper.AospMockLocationProviderManager.startMockingLocation()
  ```

- - - -

* thoughts:
  - I'm mentioning the issue of mismatched apk signatures,<br>because it's possible that you're unintentionally running into it.. by installing:
    * release build of UnifiedNlp backend plugin from github
    * release build of app from a 3rd-party..
  - I'm not sure if f-droid is distrubuting this app
    * if so.. I'm also not sure if the version that they would release is signed by me or themselves
  - if your logcat..
    * looks similar to this.. then that's the source of your problem
    * shows something else.. then I'd be very interested to see what it says
* final thoughts..
  - since you're running LineageOS..
    * please make sure that you're using the `AOSP` variation of the app
    * rather than: `GooglePlayServices` or `HuaweiMobileServices`
  - although runtime permission checks should prompt you to enable the necessary permissions (as needed)..
    * it wouldn't hurt to go into _Settings_ and make sure that all of the app's permissions are granted

**Comment by ghost** [comment]
Oh wow, thank you so much for your great help and for looking into this in such detail. I really appreciate your answer. A little bit annoying, but I was able to fix the error super easily. Thanks here for your tip about the missing notification. I didn't know that the running service would throw one / the app is depending on the notification permission. After I gave the permission, everything worked as intended. So thanks again!
