### ISSUE TITLE
Crashes on LineageOS 18.1

### ISSUE THREAD

**Issue by StickyDigit** [warren-bank/Android-Mock-Location#4]
Installed Version 002.01.07-01API from IzzyOnDroid via F-Droid on Nexus 7 2013 running LineageOS 18.1 without Gapps.

Permitted "draw over other apps", and enabled Mock my GPS (MmGPS) as Fake GPS provider in DevOpts.

The app crashes when I hit start. The first time it draws the "click to open" thing just under the status bar, and at the same time invokes the"'App keeps crashing" dialogue. If run again quickly (presumably while still in RAM) it draws the "click to open", which vanishes after a couple of seconds, and has apparently crashed silently.

Other observations :-

Fake Traveller (FT) is running fine. When I first installed MmGPS , I had to uninstall FT to be able to select MmGPS as Mock Location Provider. Reinstalling FT, I can now switch selected apps just fine. Still this app crashes on hitting start, which is a shame as I'd like to pick locations with FT, and use MmGPS to be able to pick from bookmarks... (It would be handy if bookmarks could be selected as the "front page" for your app.)

With FT installed as well, although DevOpts lets me switch selected apps, MmGPS invokes "Mocked location not applied, you must enable mock location app in Developer Options", even though MmGPS is the selected app. Uninstalling FT stops this from appearing, but MmGPS still b0rks.

With both installed, I can select FT, and it functions.

Let me know if I can test anything for you. Will build if required. Have android 7,10 and 11 to hand (All LineageOS)

**Comment by warren-bank** [comment]
Unfortunately, none of the devices that I own are supported by LineageOS.. so I haven't been able to use it for testing.

Since I'd been meaning to pick up a device that I can run it on, and since this bug needs to be fixed, and since I need to be able to reproduce the bug to see the logcat errors and subsequently test any attempted fix.. I ordered an old/inexpensive [Samsung Galaxy S5](https://wiki.lineageos.org/devices/klte) on eBay just now; it should be delivered in about a week or so. Once I get it and have LineageOS 18.1 installed.. I'll dig into this issue.

Thanks for reporting.

**Comment by warren-bank** [comment]
I just released [v02.01.08](https://github.com/warren-bank/Android-Mock-Location/releases/tag/service%2Fv02.01.08). I'd really appreciate it if you would let me know if this fixes your crash. Thanks!

**Comment by StickyDigit** [comment]
Yep. That got it :)
