### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by xmha97** [warren-bank/Android-Mock-Location#9]
Hi, thanks for your apps.
Please add the dark theme to this app.
Thanks 🙏

**Comment by warren-bank** [comment]
The UI is incredibly basic.. I'd call it utilitarian. I have no intention to add user-configurable theming. Besides, the UI is only visible briefly.. while initially configuring location.. then it's closed and the foreground service continues to work in the background.

**Comment by xmha97** [comment]
Ok, if you don't want to do that, at least add a dark theme to the app.

**Comment by andsofine** [comment]
> The UI is incredibly basic.. I'd call it utilitarian. I have no intention to add user-configurable theming. Besides, the UI is only visible briefly.. while initially configuring location.. then it's closed and the foreground service continues to work in the background.

when the map is added, the UI will matter, won't it?
since the app will no longer be just "launched, entered data"

**Comment by warren-bank** [comment]
@andsofine 
not sure what you mean by:
> when the map is added

There is no map in the UI, and I have no intention to add one.
Other apps do mapping really well.. better to use one of those.. and share a location from said app to _Mock my GPS_.
This app has a ton of Intent filters.. so it can accept geo coordinates from pretty much any app that's willing to share them.

fwiw, [OsmAnd+](https://f-droid.org/en/packages/net.osmand.plus/) is my go-to favorite.
Why try to reinvent the wheel, when you can drive a Ferrari?

**Comment by xmha97** [comment]
> Other apps do mapping really well.. better to use one of those.

I tested other apps but none of them are as good as this app, because:
1. It does not have ads.
2. It is open source.
3. It is installed on all versions of Android.
4. The application has a simple UI.

**Comment by warren-bank** [comment]
hi @xmha97
I'm glad you like the app :smiley:

allow me to clarify..
* I'm not suggesting that this app shouldn't be used
* I am suggesting that this app does one thing.. and does it well
  - it's the classic [unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy)
  - instead of adding other features to this app.. and implementing them poorly (or minimally),<br>it's better to integrate with other apps that focus on doing them properly

concretely..
* this app does location mocking
* this app is not mapping or navigation software

**Comment by xmha97** [comment]
I completely agree with you. 👍

And thanks for pointing out the unix philosophy, I knew nothing about it.

Of course, I don't agree with adding the map to the app because the app depends on "Google Play Services" and in that case not everyone can use it.

(Some Chinese phones do not have it)

**Comment by warren-bank** [comment]
Any good mapping software would work..
for the purpose to be able to pick a location on a map and communicate its lat/lon to _Mock my GPS_..
which can then use that location as a "fixed position" GPS coordinate..
and begin mocking that location (or bookmark it for later).

OsmAnd is great, but admittedly.. it's a large install.
As an example of another app that's great.. no ads.. works offline.. uses Osm.. and has a lightweight footprint:
[All-In-One Offline Maps](https://play.google.com/store/apps/details?id=net.psyberia.offlinemaps) is very nice, as well..
and its universal APK is less than 7MB.
Since its UI takes a little getting used to..
here is a quick summary of how you can use this mapping software to share geo Intents:
* there's a small circle in the center of the map
* you can drag the map so the location you want to mock is directly under that small circle
* click the small circle to open a context dialog
* click the button to the far right of "Tools.." (with an arrow pointing to the right)
* choose to "Open with..": "Other Application.."
* choose: "Mock my GPS"
* choose to "Use Geo-Intent For": "Fixed Position"
* click: "Start"
